language: python

env:
  global:
    - CODECLIMATE_REPO_TOKEN=04bbad878d8dd70115927bd5285bfe46fe78455c38a464596540f4feb9d7cf67

script:
  - python setup.py nosetests

after_script:
  - codeclimate-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
